name: Build and Push Image to DigitalOcean Registry

on:
  # Triggers the workflow on push events but only for the main and production branches
  push:
    branches: [main, production]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: "Image version"
        required: true
#2
env:
  REGISTRY: "registry.digitalocean.com/mixi-webapp"
  IMAGE_NAME: "webapp"

#3
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set environment based on branch
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "ENV=dev" >> $GITHUB_ENV
          elif [[ ${{ github.ref }} == 'refs/heads/production' ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
          fi

      - name: Build Services Container image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME)-$(echo $ENV) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_PAT }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      # - name: Remove all old images
      #   run: if [ ! -z "$(doctl registry repository list | grep "$(echo $IMAGE_NAME)")" ]; then doctl registry repository delete-manifest $(echo $IMAGE_NAME) $(doctl registry repository list-tags $(echo $IMAGE_NAME) | grep -o "sha.*") --force; else echo "No repository"; fi

      - name: Push Services image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME)-$(echo $ENV)
